name: bright_kid
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  google_fonts: ^2.1.0
  shared_preferences: ^2.0.6
  step_progress_indicator:
  animated_bottom_navigation_bar: ^0.3.2
  intl: ^0.17.0
  flutter_launcher_icons: ^0.9.0
  fluttertoast: ^8.0.8
  connectivity: ^3.0.6
  modal_progress_hud: ^0.1.3
  flutter_spinkit: ^5.0.0
  pull_to_refresh: ^2.0.0
  circular_countdown_timer: ^0.2.0
  cached_network_image: ^3.0.0
  shimmer: ^2.0.0
  image_picker: ^0.8.4


flutter_icons:
  image_path: "assets/images/appIcon.png"
  ios: true
  android: true
  remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  get: 4.1.4

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/localization/

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
    - family: MulishBlack
      fonts:
        - asset: assets/fonts/Mulish-Black.ttf
    - family: babib
      fonts:
        - asset: assets/fonts/babib.TTF



